twitter:
  query: "#EmprendeFEDES"
  consumer_key: "efjOrToCbUf6JJphiIN9A"
  consumer_secret: "WdxYZnRK4L0HBpNfWwUIC3FEC0iIKktGxnSgLSw"
  access_token: "637192024-qCTlaSioqhmhHlGfRkUyJhot6q9SI8etZlPmdK3a"
  access_token_secret: "ervh9CuhKJPTaaMqXlfpV6miRJyPeZ5dnROO93EM"
app:
  title: "#EmprendeFEDES"
